package ua.naiksoftware.waronline.res;

public enum Words {
	PASS_AND_PLAY, PLAY_ONLINE, SETTINGS, ABOUT,

	SELECT_MAP, ADD, EDIT, DELETE, SOUND, MUSIC_EFFECTS,
	INPUT_MAP_NAME, INPUT_MAP_SIZE,

	BACK, NEXT, OK, CANCEL, EXIT,

	BUILD_MAP, LOCATE_OBJECTS, UNITS_GAMER, FREE_UNITS,
	
	MIN_TWO_GAMERS_REQUIRED,
	SAVE_MAP_AND_EXIT,
        
        SIZE, MAX_GAMERS
}
