package ua.naiksoftware.waronline.map;

public enum TileCode {

    GRASS,

    TREES,

    TREES_EDGE_DOWN,
    TREES_EDGE_RIGHT,
    TREES_EDGE_UP,
    TREES_EDGE_LEFT,

    TREES_CORNER_RIGHT_DOWN,
    TREES_CORNER_LEFT_DOWN,
    TREES_CORNER_LEFT_UP,
    TREES_CORNER_RIGHT_UP,

    TREES_INCORNER_RIGHT_DOWN,
    TREES_INCORNER_LEFT_DOWN,

    ROAD_HORIZ,
    ROAD_VERT,
    ROAD_INTERSECT,

    ROAD_CORNER_RIGHT_UP,
    ROAD_CORNER_RIGHT_DOWN,
    ROAD_CORNER_LEFT_DOWN,
    ROAD_CORNER_LEFT_UP,

    ROAD_END_RIGHT,
    ROAD_END_DOWN,
    ROAD_END_LEFT,
    ROAD_END_UP,

	BRIDGE_VERT,
    BRIDGE_UP,
    BRIDGE_DOWN,
    BRIDGE_HORIZ,
    BRIDGE_LEFT,
    BRIDGE_RIGHT,

    WATER,

    WATER_DOWN_1,
    WATER_DOWN_2,
    WATER_UP_1,
    WATER_UP_2,
    WATER_LEFT_1,
    WATER_LEFT_2,
    WATER_RIGHT_1,
    WATER_RIGHT_2,

    WATER_CORNER_RIGHT_DOWN,
    WATER_CORNER_LEFT_DOWN,
    WATER_CORNER_LEFT_UP,
    WATER_CORNER_RIGHT_UP,

    WATER_INCORNER_RIGHT_DOWN,
    WATER_INCORNER_LEFT_DOWN,
    WATER_INCORNER_LEFT_UP,
    WATER_INCORNER_RIGHT_UP,

    REDUIT_1,
    REDUIT_2
}
